# Generated by Django 4.2.26 on 2025-12-02 12:19

import uuid
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("created_at", models.DateTimeField(default=timezone.now)),
            ],
        ),
    ]
